server:
  port: 8686
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
#            前端8384调后台不会出现跨域问题
            allowed-origins:
              - "http://localhost:8384"
              - "http://localhost:8282"
              - "http://localhost:8283"

            allowed-headers: "*"
            allowed-methods: "*"
            max-age: 3600
      discovery:
        locator:
          enabled: true
